import ProfileImage from './profile.jpg'
import GithubImage from "./github.jpg"
import LinkedInImage from "./linkedin-124.png"
import BadgeImage from "./badge.png"
import EducationImage from "./education.png"
import EmailImage from "./icons8-email-50.png"
import NextJsImage from  "./next.jpg"
import QuizAppSS from "./QuizSS.png"
import EcommerceSS from "./EcommerceSS.png"
import HospitalSS from "./hospitalSS.png"
export {QuizAppSS,EcommerceSS,HospitalSS, ProfileImage ,NextJsImage,GithubImage,LinkedInImage,BadgeImage,EducationImage,EmailImage}